[package]
name = "swap-controller-api"
version = "4.0.0"
edition = "2024"

[dependencies]
bitcoin = { workspace = true }
jsonrpsee = { workspace = true, features = ["macros", "server", "client-core", "http-client"] }
rust_decimal = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true, features = ["serde"] }

[lints]
workspace = true
